services:
    lmdi.purgesub.listener:
        class: lmdi\purgesub\event\main_listener
        arguments:
            - '@dbal.conn'
            - '@config'
        tags:
            - { name: event.listener }
